// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SIS_stochastic_async_cpp
Rcpp::List SIS_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIS_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIS_stochastic_hybrid_cpp
Rcpp::List SIS_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIS_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIS_stochastic_sync_cpp
Rcpp::List SIS_stochastic_sync_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIS_stochastic_sync_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_sync_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_async_cpp
Rcpp::List SIR_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIR_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_hybrid_cpp
Rcpp::List SIR_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIR_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_sync_cpp
Rcpp::List SIR_stochastic_sync_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SIR_stochastic_sync_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_sync_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SLIR_stochastic_async_cpp
Rcpp::List SLIR_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SLIR_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SLIR_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SLIR_stochastic_hybrid_cpp
Rcpp::List SLIR_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctionsEpi_SLIR_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SLIR_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// functionTimer_cpp
void functionTimer_cpp(int reps);
RcppExport SEXP _bobFunctionsEpi_functionTimer_cpp(SEXP repsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    functionTimer_cpp(reps);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bobFunctionsEpi_SIS_stochastic_async_cpp", (DL_FUNC) &_bobFunctionsEpi_SIS_stochastic_async_cpp, 1},
    {"_bobFunctionsEpi_SIS_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctionsEpi_SIS_stochastic_hybrid_cpp, 1},
    {"_bobFunctionsEpi_SIS_stochastic_sync_cpp", (DL_FUNC) &_bobFunctionsEpi_SIS_stochastic_sync_cpp, 1},
    {"_bobFunctionsEpi_SIR_stochastic_async_cpp", (DL_FUNC) &_bobFunctionsEpi_SIR_stochastic_async_cpp, 1},
    {"_bobFunctionsEpi_SIR_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctionsEpi_SIR_stochastic_hybrid_cpp, 1},
    {"_bobFunctionsEpi_SIR_stochastic_sync_cpp", (DL_FUNC) &_bobFunctionsEpi_SIR_stochastic_sync_cpp, 1},
    {"_bobFunctionsEpi_SLIR_stochastic_async_cpp", (DL_FUNC) &_bobFunctionsEpi_SLIR_stochastic_async_cpp, 1},
    {"_bobFunctionsEpi_SLIR_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctionsEpi_SLIR_stochastic_hybrid_cpp, 1},
    {"_bobFunctionsEpi_functionTimer_cpp", (DL_FUNC) &_bobFunctionsEpi_functionTimer_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bobFunctionsEpi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
