# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SIS_stochastic_async_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIS_stochastic_async_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SIS_stochastic_hybrid_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIS_stochastic_hybrid_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SIS_stochastic_sync_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIS_stochastic_sync_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SIR_stochastic_async_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIR_stochastic_async_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SIR_stochastic_hybrid_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIR_stochastic_hybrid_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SIR_stochastic_sync_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SIR_stochastic_sync_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SLIR_stochastic_async_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SLIR_stochastic_async_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

SLIR_stochastic_hybrid_cpp <- function(args) {
    .Call('_bobFunctionsEpi_SLIR_stochastic_hybrid_cpp', PACKAGE = 'bobFunctionsEpi', args)
}

functionTimer_cpp <- function(reps) {
    invisible(.Call('_bobFunctionsEpi_functionTimer_cpp', PACKAGE = 'bobFunctionsEpi', reps))
}

